### ISSUE TITLE
Create scaffolding for baseline web app

### ISSUE THREAD

**Issue by tz-earl** [helpfulengineering/project-data-platform-ts#2]
Develop a draft architecture and implement the necessary frameworks and infrastructure for the architecture.

**Comment by RobertLRead** [comment]
A very simple client-side only GithubPages implementation has been begun here: [https://helpfulengineering.github.io/project-data-platform-ts/](https://helpfulengineering.github.io/project-data-platform-ts/)

**Comment by Jbutler-helpful** [comment]
AWS infrastructure up and running

**Comment by Jbutler-helpful** [comment]
@RobertLRead "committed some code that does a very simple "hello world" webiste in Nuxt/Vue and touches (barely) an azurite backend.  Azurite is a local emulator for Azure (a global cloud service.)  Next Steps will be 1) actually reading and writing data to Azurite and 2) setting up a global Azure credentialled account which can be used similarly, and 3) creating an Azure hosted static website that renders the "hello World" app, and then 4) Expanding functional to include @elon 's GUI design.  Getting to step 4 should take about 3 hours of labor, I imgine, but it is tricky system administration stuff."

**Comment by RobertLRead** [comment]
Today @Jbutler-helpful and I added a branch with some initial code. It is correctly reaching the backend from the frontend. The backend is not yet correctly reading credentials to actually read Azure storage; that is probably what we should do next. I may need @devhawk 's help with loading those into the local-settings.json file.

**Comment by Jbutler-helpful** [comment]
This has been resolved
