### ISSUE TITLE
Enable front end to reach all OKH fields of data loaded from Azure

### ISSUE THREAD

**Issue by Jbutler-helpful** [helpfulengineering/project-data-platform-ts#30]
@ZintisMay

**Comment by ZintisMay** [comment]
As discussed, goal is to get the OKH data from Azure and have as many fields as reasonably possible to load in the product card.

**Comment by ZintisMay** [comment]
@NimeshaKahingala 

There should be a backend route for this... it should be 

/getFile/okh/bread/yml

something like that... check the /listRoutes

**Comment by ZintisMay** [comment]
/getFile/okh/bread/yml

route should do the trick
/listRoutes to see file list

**Comment by ZintisMay** [comment]
Api routes exist to access file lists in containers and individual files, still need to be integrated with front more fully. Future tasks will include caching, memoization, etc... to make the process smoother.
