### ISSUE TITLE
Convert JSON Blobs on backend into Typescript types in the front end...

### ISSUE THREAD

**Issue by RobertLRead** [helpfulengineering/project-data-platform-ts#35]
Note: I think we may NOT need to use the typescript types on the backend, because the data has to be transferreed as JSON anyway.

Note: You will see examples already of having to take each field of the object by hand. There are fancier ways of creating a typescirpt object from JSON using "Object.???" in some way, but it is tricky (see StackExcchange for examples.)

**Comment by ZintisMay** [comment]
Notes for myself:

1. Move types folder up (see other ticket)
2. have front end reference those types when receiving data from back
3. have back reference those types before sending the data (optional, maybe do later)
4. convert example data into a format matching the types

**Comment by ZintisMay** [comment]
At the weekly meeting we decided just to ferry the data to the front. The TS types are good and well but getting the data up front is more important. 

This related to the ticket where we would have TS types on the back-end, but having both sides share the same file imports proved to be more complicated than it's worth.

**Comment by ZintisMay** [comment]
That being said, we are currently able to get the data in JSON format from back to front.
