### ISSUE TITLE
 Read OKHs & OKWs from S3

### ISSUE THREAD

**Issue by tz-earl** [helpfulengineering/project-data-platform-ts#4]

**Comment by Jbutler-helpful** [comment]
Robert you mentioned OKH are being read, what is the plan for OKW's

**Comment by devhawk** [comment]
I will create an azure function backend service to provide OKHs and OKWs

**Comment by devhawk** [comment]
We are blocked waiting on figuring out our azure non profit status

**Comment by RobertLRead** [comment]
This is obsolete, we are now using Azure.
