### ISSUE TITLE
Move types file to /packages folder so that all project parts can read from it equally

### ISSUE THREAD

**Issue by ZintisMay** [helpfulengineering/project-data-platform-ts#45]
![image](https://github.com/user-attachments/assets/6bb5fd83-34a5-4145-8bb8-ee31c74282ca)

just move the file folder out and up, and change all the file paths

**Comment by ZintisMay** [comment]
@RobertLRead This ended up being more complicated than I bargained for. the TS process can only access files in the root directory (front-end, back-end). So going up a level won't work. I looked around in forums and such for other solutions, but they require things like making the entire repo a TS project (with a TS config) or custom NPM packages, which I think are much heavier solutions than we want to be doing at this point. 

I propose we just copy the file, and leave a note saying to sync the files when updated.

**Comment by RobertLRead** [comment]
Okay.

**Comment by ZintisMay** [comment]
At the meeting we decided to move fast and get stuff done. This particular task seems to take more time than it would benefit us.
