### ISSUE TITLE
Port existing python atom code to TypeScript

### ISSUE THREAD

**Issue by tz-earl** [helpfulengineering/project-data-platform-ts#6]
TypeScript??

**Comment by Jbutler-helpful** [comment]
Yes TypeScript

**Comment by devhawk** [comment]
> TypeScript??

Yes Typescript

**Comment by Jbutler-helpful** [comment]
@devhawk Robert mentioned you where working on this, is this correct?

**Comment by devhawk** [comment]
I have not, but it shouldn't be too tough

**Comment by devhawk** [comment]
This was merged into main in commit afa8a9596f54b2ee50f08376018b79d602923f98

**Comment by Jbutler-helpful** [comment]
@devhawk still needs to supply tree query code

**Comment by devhawk** [comment]
Finished porting supply tree query in commit hash bf8cf8c1f670a3e764a515c1868760d7a9fc4f42
