### ISSUE TITLE
Investigate reading large JSON files directly from GitHub Pages (NOT the Github API) as a means of loading OKHs....

### ISSUE THREAD

**Issue by RobertLRead** [helpfulengineering/project-data-platform-ts#8]
For example, this directory in the repo:

[https://github.com/helpfulengineering/library/tree/main/beta/okh](https://github.com/helpfulengineering/library/tree/main/beta/okh)

But also @devhawk may have translated a bunch of recipe JSON in an S3 object; but we may be able to do it as a raw file.

**Comment by Jbutler-helpful** [comment]
We have moved over to Azure blob storage
